apiVersion: v1
kind: Service
metadata:
  name: aceest-ab-service
  labels:
    project: aceest-fitness
spec:
  selector:
    app: aceest-ab
    track: a   # <-- This is what we change to route users
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort