apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-version-b
  labels:
    project: aceest-fitness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest-ab
      track: b
  template:
    metadata:
      labels:
        app: aceest-ab
        track: b
        project: aceest-fitness
    spec:
      containers:
      - name: aceest
        image: 2024tm93564/aceest-fitness:v3.2.4
        ports:
        - containerPort: 5000