apiVersion: v1
kind: Service
metadata:
  name: aceest-live-service
  labels:
    project: aceest-fitness
spec:
  selector:
    app: aceest-live
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort